# Generated by Django 4.1.7 on 2023-02-25 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ('turno', 'id')},
        ),
    ]
